#!/usr/bin/expect -f

set ip [lindex $argv 0]

set port [lindex $argv 1]

set password [lindex $argv 2]
set file [lindex $argv 3]

# set oper 9
# send "$oper"

spawn ssh -p $port root@$ip

set timeout 300

expect "password"

send "$password\r"

expect "root"
send "cd /www/sites/go\r"

expect "root"
send "killall releaseTimeoutTask.bin\r"

expect "root"
send "nohup ./$file &\r"

expect eof # 结束或者执行下边一行命令
# interact #操作完成(停留在登录状态)
