#!/usr/bin/expect -f

set ip [lindex $argv 0]

set port [lindex $argv 1]

set password [lindex $argv 2]
set file [lindex $argv 3]
set path [lindex $argv 4]

# set oper 9
# send "$oper"

spawn scp -P $port $file root@$ip:$path

set timeout 300

expect "password"

send "$password\r"

expect eof
# interact #操作完成(停留在登录状态)
