[Master]
    Driver = "mysql"
    EnableQueryLog = false
    SetMaxOpenConns = 0
    SetMaxIdleConns = 0
    Prefix = ""
    Dsn = "username:password@tcp(localhost:5555)/dbname?charset=utf8"
[[Slave]]
    Driver = "mysql"
    EnableQueryLog = false
    SetMaxOpenConns = 0
    SetMaxIdleConns = 0
    Prefix = ""
    Dsn = "username:password@tcp(localhost:5555)/dbname?charset=utf8"
[[Slave]]
    Driver = "mysql"
    EnableQueryLog = false
    SetMaxOpenConns = 0
    SetMaxIdleConns = 0
    Prefix = ""
    Dsn = "username:password@tcp(localhost:5555)/dbname?charset=utf8"
